use my_db;
use main;
create or replace sequence weather_seq;

create or replace table my_db.main.silver_weather (
    weather_sk bigint primary key default nextval('weather_seq'),
    city_name varchar(100),
    country_code varchar(10),
    datetime timestamp,
    temperature float,
    app_temperature float,
    dew_point_temperature float,
    cloud_cover int,
    high_cloud_cover int,
    mid_cloud_cover int,
    low_cloud_cover int,
    probability_of_precipitation int,
    precipitation float,
    snow int,
    snow_depth int,
    pressure int,
    sea_level_pressure int,
    relative_humidity int,
    diffuse_horizontal_irradiance int,
    direct_normal_irradiance int,
    global_horizontal_irradiance int,
    solar_radiation float,
    uv int,
    visibility float,
    wind_cardinal_direction varchar(10),
    wind_direction int,
    gust_speed float,
    wind_speed float,
    part_of_day varchar(10),
    ozone int,
    weather_icon varchar(100),
    weather_code varchar(10),
    weather_description varchar,
    ingested_at timestamp default current_timestamp
);

insert into my_db.main.silver_weather (
    city_name,
    country_code,
    datetime,
    temperature,
    app_temperature,
    dew_point_temperature,
    cloud_cover,
    high_cloud_cover,
    mid_cloud_cover,
    low_cloud_cover,
    probability_of_precipitation,
    precipitation,
    snow,
    snow_depth,
    pressure,
    sea_level_pressure,
    relative_humidity,
    diffuse_horizontal_irradiance,
    direct_normal_irradiance,
    global_horizontal_irradiance,
    solar_radiation,
    uv,
    visibility,
    wind_cardinal_direction,
    wind_direction,
    gust_speed,
    wind_speed,
    part_of_day,
    ozone,
    weather_icon,
    weather_code,
    weather_description
)

select
    cast(data->>'$.city_name' as varchar),
    cast(data->>'$.country_code' as varchar),
    cast(replace(data->>'$.datetime', ':', ' ') || ':00:00' as timestamp),
    cast(data->>'$.temp' as float),
    cast(data->>'$.app_temp' as float),
    cast(data->>'$.dewpt' as float),
    cast(data->>'$.clouds' as int),
    cast(data->>'$.clouds_hi' as int),
    cast(data->>'$.clouds_mid' as int),
    cast(data->>'$.clouds_low' as int),
    cast(data->>'$.pop' as int),
    cast(data->>'$.precip' as float),
    cast(data->>'$.snow' as int),
    cast(data->>'$.snow_depth' as int),
    cast(data->>'$.pres' as int),
    cast(data->>'$.slp' as int),
    cast(data->>'$.rh' as int),
    cast(data->>'$.dhi' as int),
    cast(data->>'$.dni' as int),
    cast(data->>'$.ghi' as int),
    cast(data->>'$.solar_rad' as float),
    cast(data->>'$.uv' as int),
    cast(data->>'$.vis' as float),
    cast(data->>'$.wind_cdir' as varchar),
    cast(data->>'$.wind_dir' as int),
    cast(data->>'$.wind_gust_spd' as float),
    cast(data->>'$.wind_spd' as float),
    cast(data->>'$.pod' as varchar),
    cast(data->>'$.ozone' as int),
    cast(data->>'$.weather_icon' as varchar),
    cast(data->>'$.weather_code' as varchar),
    cast(data->>'$.weather_description' as varchar)
from my_db.main.bronze_weather;
